### ISSUE TITLE
Package depends on itself

### ISSUE THREAD

**Issue by rskew** [python-openxml/opc-diag#12]
I'm trying to install `opc-diag` in a [pixi](https://github.com/prefix-dev/pixi) project, but the solver fails (by consuming all RAM :sweat_smile: ), I think due to `opc-diag` depending on itself.

The entry `opc-diag` in the dependencies of `pyproject.toml` probably shouldn't be there. Could it be removed?

Thanks for your consideration

**Comment by scanny** [comment]
k, should be fixed by #13, let me know if it gives you trouble :)
